import type { Plan, Alert, ActionLog, StoreConfig, Category } from '../types/database'

export const mockStoreConfig: StoreConfig = {
  id: '1',
  created_at: new Date().toISOString(),
  store_name: '全站推广店铺',
  gross_margin_rate: 0.31,
  t2_net_margin_rate: 0.06,
  t2_cost_rate: 0.25,
  weekly_margin_target: 0.10,
  weekly_actual_margin: 0.082,
}

export const mockPlans: Plan[] = [
  {
    id: '1', created_at: '', updated_at: '',
    name: '女装-春季新款-A',
    category_id: '1',
    roi_target: 7,
    daily_budget: 500,
    bid_mode: 'roi',
    bid_objective: 'net',
    anti_stop_enabled: true,
    multi_target_enabled: false,
    quick_boost_enabled: false,
    budget_type: 'daily',
    zone: 'green',
    confidence: 'H',
    is_active: true,
    gross_margin_rate: 0.31,
    spend_today: 320,
    revenue_today: 2800,
    roi_completion_rate: 1.28,
    cost_rate_today: 0.114,
  },
  {
    id: '2', created_at: '', updated_at: '',
    name: '女装-基础款-B',
    category_id: '1',
    roi_target: 6,
    daily_budget: 300,
    bid_mode: 'roi',
    bid_objective: 'net',
    anti_stop_enabled: false,
    multi_target_enabled: false,
    quick_boost_enabled: false,
    budget_type: 'daily',
    zone: 'yellow',
    confidence: 'M',
    is_active: true,
    gross_margin_rate: 0.28,
    spend_today: 210,
    revenue_today: 1050,
    roi_completion_rate: 0.83,
    cost_rate_today: 0.20,
  },
  {
    id: '3', created_at: '', updated_at: '',
    name: '配饰-爆款-C',
    category_id: '2',
    roi_target: 5,
    daily_budget: 200,
    bid_mode: 'roi',
    bid_objective: 'net',
    anti_stop_enabled: false,
    multi_target_enabled: false,
    quick_boost_enabled: false,
    budget_type: 'daily',
    zone: 'red',
    confidence: 'H',
    is_active: true,
    gross_margin_rate: 0.25,
    spend_today: 180,
    revenue_today: 620,
    roi_completion_rate: 0.69,
    cost_rate_today: 0.29,
  },
  {
    id: '4', created_at: '', updated_at: '',
    name: '女装-大码-D',
    category_id: '1',
    roi_target: 8,
    daily_budget: 400,
    bid_mode: 'roi',
    bid_objective: 'net',
    anti_stop_enabled: true,
    multi_target_enabled: false,
    quick_boost_enabled: false,
    budget_type: 'daily',
    zone: 'green',
    confidence: 'H',
    is_active: true,
    gross_margin_rate: 0.33,
    spend_today: 280,
    revenue_today: 2800,
    roi_completion_rate: 1.25,
    cost_rate_today: 0.10,
  },
  {
    id: '5', created_at: '', updated_at: '',
    name: '鞋靴-新品-E',
    category_id: '3',
    roi_target: 4,
    daily_budget: 150,
    bid_mode: 'roi',
    bid_objective: 'net',
    anti_stop_enabled: false,
    multi_target_enabled: true,
    quick_boost_enabled: false,
    budget_type: 'daily',
    zone: 'yellow',
    confidence: 'L',
    is_active: true,
    gross_margin_rate: 0.30,
    spend_today: 80,
    revenue_today: 280,
    roi_completion_rate: 0.875,
    cost_rate_today: 0.286,
  },
]

export const mockAlerts: Alert[] = [
  {
    id: '1', created_at: new Date().toISOString(),
    plan_id: '3', plan_name: '配饰-爆款-C',
    rule_code: 'R2-B',
    severity: 'red',
    title: '🔴 R2-B 红区止损',
    detail: '当日累计费比 29.0% > Gross毛利率 25.0%，已进入红区亏损状态',
    action_text: '净目标投产比 → max(5.0, 止损ROI×1.1=4.40) → 设为 5.50 | 剩余预算 × 0.6',
    status: 'pending',
    confirmed_at: null,
    confirmed_note: null,
    inspection_point: '18:00',
  },
  {
    id: '2', created_at: new Date().toISOString(),
    plan_id: '2', plan_name: '女装-基础款-B',
    rule_code: 'R1-B',
    severity: 'yellow',
    title: '🟡 R1-B 费比偏高预警',
    detail: '计划费比 20.0% > 全店累计费比 17.5%，预估全天收益 < 昨日花费',
    action_text: '净目标投产比 × 1.15 → 6.9 | 剩余预算 × 0.8',
    status: 'pending',
    confirmed_at: null,
    confirmed_note: null,
    inspection_point: '16:00',
  },
  {
    id: '3', created_at: new Date(Date.now() - 3600000).toISOString(),
    plan_id: '1', plan_name: '女装-春季新款-A',
    rule_code: 'R3',
    severity: 'green',
    title: '🟢 R3 绿区加预算',
    detail: 'ROI完成率 128%，剩余预算不足3小时均值花费，绿区高置信度',
    action_text: '今日每日预算 + 18% → ¥590 | 确认防停投已开启',
    status: 'confirmed',
    confirmed_at: new Date(Date.now() - 3600000).toISOString(),
    confirmed_note: '已执行，预算追加完成',
    inspection_point: '16:00',
  },
  {
    id: '4', created_at: new Date(Date.now() - 7200000).toISOString(),
    plan_id: null, plan_name: '全店',
    rule_code: 'STORE',
    severity: 'indigo',
    title: '📊 全店毛利余量提醒',
    detail: '本周全店净毛利 8.2%，低于目标 10%，余量 -1.8%，进入"收紧"模式',
    action_text: '黄区计划每日预算×0.75 + ROI目标上调10%；18:00黄区禁入晚高峰',
    status: 'auto',
    confirmed_at: null,
    confirmed_note: null,
    inspection_point: '09:00',
  },
]

export const mockActionLog: ActionLog[] = [
  {
    id: '1', created_at: new Date(Date.now() - 1800000).toISOString(),
    plan_id: '1', plan_name: '女装-春季新款-A',
    rule_code: 'R3',
    action: '追加今日每日预算',
    old_roi: 7, new_roi: 7,
    old_budget: 500, new_budget: 590,
    status: 'confirmed',
    note: '已执行，预算追加完成',
    operator: '人工确认',
  },
  {
    id: '2', created_at: new Date(Date.now() - 10800000).toISOString(),
    plan_id: '2', plan_name: '女装-基础款-B',
    rule_code: 'DT1',
    action: '天规则：ROI上调 + 预算轻压',
    old_roi: 5.5, new_roi: 6.0,
    old_budget: 330, new_budget: 300,
    status: 'auto',
    note: null,
    operator: '系统自动',
  },
  {
    id: '3', created_at: new Date(Date.now() - 86400000).toISOString(),
    plan_id: '3', plan_name: '配饰-爆款-C',
    rule_code: 'R2-A',
    action: 'ROI上调18% + 剩余预算×0.7',
    old_roi: 4.5, new_roi: 5.0,
    old_budget: 220, new_budget: 200,
    status: 'confirmed',
    note: '情况好转后恢复观察',
    operator: '人工确认',
  },
]

export const mockCategories: Category[] = [
  {
    id: '1', created_at: '',
    name: '女装',
    avg_add_to_cart_rate: 0.08,
    avg_conversion_rate: 0.12,
    avg_unit_price: 180,
    avg_cost_rate: 0.18,
    cart_to_order_delay_p50: 2,
    cart_to_order_delay_p80: 7,
    coldstart_days_p80: 14,
  },
  {
    id: '2', created_at: '',
    name: '配饰',
    avg_add_to_cart_rate: 0.05,
    avg_conversion_rate: 0.15,
    avg_unit_price: 80,
    avg_cost_rate: 0.22,
    cart_to_order_delay_p50: 1,
    cart_to_order_delay_p80: 4,
    coldstart_days_p80: 10,
  },
  {
    id: '3', created_at: '',
    name: '鞋靴',
    avg_add_to_cart_rate: 0.06,
    avg_conversion_rate: 0.10,
    avg_unit_price: 280,
    avg_cost_rate: 0.20,
    cart_to_order_delay_p50: 3,
    cart_to_order_delay_p80: 10,
    coldstart_days_p80: 18,
  },
]
